name: ivexes
services:
  nvim-lsp:
    build: ./container/nvim_lsp
    image: nvim-lsp:latest
    pull_policy: never
    ports:
      - "8080:8080"

  kali:
      build: ./container/kali_sandbox
      image: kali-ssh:latest
      pull_policy: never
      ports:
        - "2222:22"

