name: ivexes
services:
  nvim-lsp:
    build: ./container/nvim_lsp
    image: nvim-lsp:latest
    container_name: nvim-lsp
    pull_policy: never
#    ports:
#      - "2222:22"
    volumes:
      - ./workspace:/workspace:ro

  kali:
      build: ./container/kali_sandbox
      image: kali-ssh:latest
      pull_policy: never
      ports:
        - "2222:22"
      volumes:
      - ./workspace:/root/workspace:rw

