site_name: IVExES
site_url: https://pages.faigle.dev/ivexes/
theme:
  name: material
  features:
    # Allows copying code blocks
    - content.code.copy
    # Allows selecting code blocks
    - content.code.select
    # Shows the current path in the sidebar
    - navigation.path
    # Shows sections in the sidebar
    - navigation.sections
    # Shows sections expanded by default
    - navigation.expand
    # Enables annotations in code blocks
    - content.code.annotate
  palette:
    primary: black
  logo: assets/logo.png

repo_name: ivexes
repo_url: https://github.com/LetsDrinkSomeTea/ivexes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/ivexes"]
          selection:
            docstring_style: google
          options:
            # Shows links to other members in signatures
            signature_crossrefs: true
            # Orders members by source order, rather than alphabetical
            members_order: source
            # Puts the signature on a separate line from the member name
            separate_signature: true
            # Shows type annotations in signatures
            show_signature_annotations: true
            # Makes the font sizes nicer
            heading_level: 3
            # Show inherited members
            inherited_members: true

extra:
  # Remove material generation message in footer
  generator: false
  language: en

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

nav:
  - Home: index.md
  - API Reference:
    - Agents: agents.md
    - Code Browser: code_browser.md
    - Configuration: config.md
    - CVE Search: cve_search.md
    - Sandbox: sandbox.md
    - Tools: tools.md
    - Vector Database: vector_db.md

watch:
  - "src/ivexes"
