site_name: IVExES
site_url: https://pages.faigle.dev/ivexes/
theme:
  name: material
  features:
    # Allows copying code blocks
    - content.code.copy
    # Allows selecting code blocks
    - content.code.select
    # Shows the current path in the sidebar
    - navigation.path
    # Shows sections in the sidebar
    - navigation.sections
    # Shows sections expanded by default
    - navigation.expand
    # Enables annotations in code blocks
    - content.code.annotate
  palette:
    primary: black
  logo: assets/logo.png

repo_name: ivexes
repo_url: https://github.com/LetsDrinkSomeTea/ivexes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/ivexes"]
          selection:
            docstring_style: google
          options:
            # Shows links to other members in signatures
            signature_crossrefs: true
            # Orders members by source order, rather than alphabetical
            members_order: source
            # Puts the signature on a separate line from the member name
            separate_signature: true
            # Shows type annotations in signatures
            show_signature_annotations: true
            # Makes the font sizes nicer
            heading_level: 3
            # Show inherited members
            inherited_members: true

extra:
  # Remove material generation message in footer
  generator: false
  language: en

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Documentation:
    - Architecture: documentation/architecture.md
    - Installation: documentation/installation.md
    - Configuration: documentation/configuration.md
    - Usage Guide: documentation/usage.md
    - Examples: documentation/examples.md
    - Development: documentation/development.md
  - API Reference:
    - Agents: api/agents.md
    - Code Browser: api/code_browser.md
    - Configuration: api/config.md
    - CVE Search: api/cve_search.md
    - Sandbox: api/sandbox.md
    - Tools: api/tools.md
    - Vector Database: api/vector_db.md

watch:
  - "src/ivexes"
