on:
  push:
  workflow_dispatch:

jobs:
  requirements:
    name: Check python requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python3 tests/run_tests.py
      - name: init
        run: |
          python3 manual.py --help
