name: Check Requirements
on:
  push:
  workflow_dispatch:

jobs:
  requirements:
    name: Check python requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          pip install .
      - name: build container
        run: |
          docker compose build
      - name: run app
        run: |
          python3 src/ivexes/manual.py --help
      - name: query vectordb
        run: |
          python3 src/ivexes/manual.py vector-db query test-value
