name: Integration Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    name: Check Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - name: Build container
        run: |
          docker compose build
      
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      
      - name: Test CLI help
        run: |
          python3 examples/manual.py --help
        env:
          LLM_API_KEY: sk-test-key-for-validation
      
      - name: Test vector database query
        run: |
          python3 examples/manual.py vector-db query test-value
        env:
          LLM_API_KEY: sk-test-key-for-validation
      
      - name: Test configuration validation
        run: |
          python3 -c "from ivexes.config.settings import get_settings; print(get_settings())"
        env:
          LLM_API_KEY: sk-test-key-for-validation
