name: Integration Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-images:
    name: Check Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build container
        run: |
          docker compose build
          make build-images
      
  litellm:
    name: Check Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run litellm container
        run: |
          make run-litellm 

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Install dependencies
        run: |
          uv sync
      
      - name: Test CLI help
        run: |
          uv run python manual.py --help
        env:
          LLM_API_KEY: sk-test-key-for-validation
      
      - name: Test vector database query
        run: |
          uv run python manual.py vector-db query test-value
        env:
          LLM_API_KEY: sk-test-key-for-validation
